-- Migration: Add billing fields to membership and subscription_payments
-- Generated by Menucom API development

-- =============================================
-- MEMBERSHIP TABLE - New Billing Fields
-- =============================================

-- Add billing mode enum (requires creating enum type first in PostgreSQL)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'billingmode') THEN
        CREATE TYPE billingmode AS ENUM ('none', 'manual', 'auto');
    END IF;
EXCEPTION
    WHEN others THEN NULL;
END$$;

-- Add billing fields to membership
ALTER TABLE "membership" ADD COLUMN IF NOT EXISTS "billingMode" VARCHAR(20) DEFAULT 'none';
ALTER TABLE "membership" ADD COLUMN IF NOT EXISTS "adminSetPrice" DECIMAL(10,2);
ALTER TABLE "membership" ADD COLUMN IF NOT EXISTS "paidPeriodMonths" INTEGER DEFAULT 1;
ALTER TABLE "membership" ADD COLUMN IF NOT EXISTS "pendingPaymentId" VARCHAR;
ALTER TABLE "membership" ADD COLUMN IF NOT EXISTS "pendingPaymentLink" VARCHAR;
ALTER TABLE "membership" ADD COLUMN IF NOT EXISTS "pendingPaymentExpiresAt" TIMESTAMP;
ALTER TABLE "membership" ADD COLUMN IF NOT EXISTS "accessStartDate" TIMESTAMP;

-- =============================================
-- SUBSCRIPTION_PAYMENTS TABLE - New Fields
-- =============================================

ALTER TABLE "subscription_payments" ADD COLUMN IF NOT EXISTS "periodMonths" INTEGER DEFAULT 1;
ALTER TABLE "subscription_payments" ADD COLUMN IF NOT EXISTS "isAdminGenerated" BOOLEAN DEFAULT false;
ALTER TABLE "subscription_payments" ADD COLUMN IF NOT EXISTS "planName" VARCHAR;
ALTER TABLE "subscription_payments" ADD COLUMN IF NOT EXISTS "description" VARCHAR;
ALTER TABLE "subscription_payments" ADD COLUMN IF NOT EXISTS "paymentMetadata" JSONB;

-- Update payment_type enum to include MANUAL_PAYMENT
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'paymenttype') THEN
        -- Add to existing enum if PostgreSQL
        -- Note: You may need to manually update the enum in Supabase dashboard
        NULL;
    END IF;
EXCEPTION
    WHEN others THEN NULL;
END$$;

-- =============================================
-- INDEXES for better query performance
-- =============================================

CREATE INDEX IF NOT EXISTS "idx_membership_billingMode" ON "membership"("billingMode");
CREATE INDEX IF NOT EXISTS "idx_membership_pendingPaymentId" ON "membership"("pendingPaymentId");
CREATE INDEX IF NOT EXISTS "idx_membership_mpPreapprovalId" ON "membership"("mpPreapprovalId");
CREATE INDEX IF NOT EXISTS "idx_subscription_payments_membershipId" ON "subscription_payments"("membershipId");
CREATE INDEX IF NOT EXISTS "idx_subscription_payments_type" ON "subscription_payments"("type");
CREATE INDEX IF NOT EXISTS "idx_subscription_payments_isAdminGenerated" ON "subscription_payments"("isAdminGenerated");

-- =============================================
-- ROLLBACK (if needed)
-- =============================================

-- ALTER TABLE "membership" DROP COLUMN IF EXISTS "billingMode";
-- ALTER TABLE "membership" DROP COLUMN IF EXISTS "adminSetPrice";
-- ALTER TABLE "membership" DROP COLUMN IF EXISTS "paidPeriodMonths";
-- ALTER TABLE "membership" DROP COLUMN IF EXISTS "pendingPaymentId";
-- ALTER TABLE "membership" DROP COLUMN IF EXISTS "pendingPaymentLink";
-- ALTER TABLE "membership" DROP COLUMN IF EXISTS "pendingPaymentExpiresAt";
-- ALTER TABLE "membership" DROP COLUMN IF EXISTS "accessStartDate";

-- ALTER TABLE "subscription_payments" DROP COLUMN IF EXISTS "periodMonths";
-- ALTER TABLE "subscription_payments" DROP COLUMN IF EXISTS "isAdminGenerated";
-- ALTER TABLE "subscription_payments" DROP COLUMN IF EXISTS "planName";
-- ALTER TABLE "subscription_payments" DROP COLUMN IF EXISTS "description";
-- ALTER TABLE "subscription_payments" DROP COLUMN IF EXISTS "paymentMetadata";

-- DROP INDEX IF EXISTS "idx_membership_billingMode";
-- DROP INDEX IF EXISTS "idx_membership_pendingPaymentId";
-- DROP INDEX IF EXISTS "idx_membership_mpPreapprovalId";
-- DROP INDEX IF EXISTS "idx_subscription_payments_membershipId";
-- DROP INDEX IF EXISTS "idx_subscription_payments_type";
-- DROP INDEX IF EXISTS "idx_subscription_payments_isAdminGenerated";